{% set name = "sdtfile" %}
{% set version = "2020.12.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1757ea99e021643e12c20a85f8dd09a41f48811c0db58f75913d2ddcf7dac427

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.15.1
    - python >=3.6

test:
  imports:
    - sdtfile
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.lfd.uci.edu/~gohlke/
  summary: Read Becker & Hickl SDT files
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/cgohlke/sdtfile

extra:
  recipe-maintainers:
    - s-weigand
